CREATE
OR REPLACE FORCE EDITIONABLE VIEW "HR_WA_NOTIF_RELIGION_V" (
    "EMPLOYEE_ID",
    "NAME"
) AS
select
    "EMPLOYEE_ID",
    FIRST_NAME || MIDDLE_NAME || LAST_NAME AS "NAME"
from
    HR_WA_PERSONAL_V
where
    RELIGION is null;